src/Entity/OptAd.php
<?php

namespace App\Entity;

use App\Repository\OptAdRepository;
use Doctrine\ORM\Mapping as ORM;
// Fields with floating point variables are stored as string types to avoid possible problems with floating point precision number

/**
 * @ORM\Entity(repositoryClass=OptAdRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class OptAd
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=3)
     */
    private $currency;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $urls;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Tags;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $estimated_revenue;

    /**
     * @ORM\Column(type="integer")
     */
    private $ad_impressions;

    /**
     * @ORM\Column(type="string", length=4)
     */
    private $ad_ecpm;

    /**
     * @ORM\Column(type="integer")
     */
    private $clicks;

    /**
     * @ORM\Column(type="string", length=4)
     */
    private $ad_ctr;

    /**
     * @ORM\Column(type="datetime")
     */
    private $requested_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    public function setCurrency(string $currency): self
    {
        $this->currency = $currency;

        return $this;
    }

    public function getUrls(): ?string
    {
        return $this->urls;
    }

    public function setUrls(string $urls): self
    {
        $this->urls = $urls;

        return $this;
    }

    public function getTags(): ?string
    {
        return $this->Tags;
    }

    public function setTags(string $Tags): self
    {
        $this->Tags = $Tags;

        return $this;
    }

    public function getDate(): ?string
    {
        return $this->date;
    }

    public function setDate(string $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getEstimatedRevenue(): ?string
    {
        return $this->estimated_revenue;
    }

    public function setEstimatedRevenue(string $estimated_revenue): self
    {
        $this->estimated_revenue = $estimated_revenue;

        return $this;
    }

    public function getAdImpressions(): ?int
    {
        return $this->ad_impressions;
    }

    public function setAdImpressions(int $ad_impressions): self
    {
        $this->ad_impressions = $ad_impressions;

        return $this;
    }

    public function getAdEcpm(): ?string
    {
        return $this->ad_ecpm;
    }

    public function setAdEcpm(string $ad_ecpm): self
    {
        $this->ad_ecpm = $ad_ecpm;

        return $this;
    }

    public function getClicks(): ?int
    {
        return $this->clicks;
    }

    public function setClicks(int $clicks): self
    {
        $this->clicks = $clicks;

        return $this;
    }

    public function getAdCtr(): ?string
    {
        return $this->ad_ctr;
    }

    public function setAdCtr(string $ad_ctr): self
    {
        $this->ad_ctr = $ad_ctr;

        return $this;
    }

    public function getRequestedAt(): ?\DateTimeInterface
    {
        return $this->requested_at;
    }

    public function setRequestedAt(\DateTimeInterface $requested_at): self
    {
        $this->requested_at = $requested_at;

        return $this;
    }

    /**
     * @ORM\PrePersist
     */
    public function autoSetRequestedAt()
    {
        $this->requested_at = new \DateTime();
    }
}

src/Entity/SavedIMGWMeasurement.php
<?php

namespace App\Entity;

use App\Repository\SavedIMGWMeasurementRepository;
use Doctrine\ORM\Mapping as ORM;
// Fields with floating point variables are stored as string types to avoid possible problems with floating point precision number

/**
 * @ORM\Entity(repositoryClass=SavedIMGWMeasurementRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class SavedIMGWMeasurement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $station_id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $station;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=16)
     */
    private $temp;

    /**
     * @ORM\Column(type="integer")
     */
    private $wind_dir;

    /**
     * @ORM\Column(type="integer")
     */
    private $wind_speed;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $relative_humidity;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $drop_sum;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $pressure;

    /**
     * @ORM\Column(type="datetime")
     */
    private $requested_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStationId(): ?int
    {
        return $this->station_id;
    }

    public function setStationId(int $station_id): self
    {
        $this->station_id = $station_id;

        return $this;
    }

    public function getStation(): ?string
    {
        return $this->station;
    }

    public function setStation(string $station): self
    {
        $this->station = $station;

        return $this;
    }

    public function getDate(): ?string
    {
        return $this->date;
    }

    public function setDate(string $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getTemp(): ?string
    {
        return $this->temp;
    }

    public function setTemp(string $temp): self
    {
        $this->temp = $temp;

        return $this;
    }

    public function getWindDir(): ?int
    {
        return $this->wind_dir;
    }

    public function setWindDir(int $wind_dir): self
    {
        $this->wind_dir = $wind_dir;

        return $this;
    }

    public function getWindSpeed(): ?int
    {
        return $this->wind_speed;
    }

    public function setWindSpeed(int $wind_speed): self
    {
        $this->wind_speed = $wind_speed;

        return $this;
    }

    public function getRelativeHumidity(): ?string
    {
        return $this->relative_humidity;
    }

    public function setRelativeHumidity(string $relative_humidity): self
    {
        $this->relative_humidity = $relative_humidity;

        return $this;
    }

    public function getDropSum(): ?int
    {
        return $this->drop_sum;
    }

    public function setDropSum(int $drop_sum): self
    {
        $this->drop_sum = $drop_sum;

        return $this;
    }

    public function getPressure(): ?string
    {
        return $this->pressure;
    }

    public function setPressure(string $pressure): self
    {
        $this->pressure = $pressure;

        return $this;
    }

    public function getRequestedAt(): ?\DateTimeInterface
    {
        return $this->requested_at;
    }

    public function setRequestedAt(\DateTimeInterface $requested_at): self
    {
        $this->requested_at = $requested_at;

        return $this;
    }

    /**
     * @ORM\PrePersist
     */
    public function autoSetRequestedAt()
    {
        $this->requested_at = new \DateTime();
    }
}

src/Entity/SavedLanguageRecognitionDetection.php
<?php

namespace App\Entity;

use App\Repository\SavedLanguageRecognitionDetectionRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SavedLanguageRecognitionDetectionRepository::class)
 */
class SavedLanguageRecognitionDetection
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=3)
     */
    private $recognized_lang;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isReliable;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $confidence_score;

    /**
     * @ORM\ManyToOne(targetEntity=SavedLanguageRecognitionRequest::class, inversedBy="recognitions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $savedLanguageRecognitionRequest;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRecognizedLang(): ?string
    {
        return $this->recognized_lang;
    }

    public function setRecognizedLang(string $recognized_lang): self
    {
        $this->recognized_lang = $recognized_lang;

        return $this;
    }

    public function getIsReliable(): ?bool
    {
        return $this->isReliable;
    }

    public function setIsReliable(bool $isReliable): self
    {
        $this->isReliable = $isReliable;

        return $this;
    }

    public function getConfidenceScore(): ?string
    {
        return $this->confidence_score;
    }

    public function setConfidenceScore(string $confidence_score): self
    {
        $this->confidence_score = $confidence_score;

        return $this;
    }

    public function getSavedLanguageRecognitionRequest(): ?SavedLanguageRecognitionRequest
    {
        return $this->savedLanguageRecognitionRequest;
    }

    public function setSavedLanguageRecognitionRequest(?SavedLanguageRecognitionRequest $savedLanguageRecognitionRequest): self
    {
        $this->savedLanguageRecognitionRequest = $savedLanguageRecognitionRequest;

        return $this;
    }
}

src/Entity/SavedLanguageRecognitionRequest.php
<?php

namespace App\Entity;

use App\Repository\SavedLanguageRecognitionRequestRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
// Fields with floating point variables are stored as string types to avoid possible problems with floating point precision number

/**
 * @ORM\Entity(repositoryClass=SavedLanguageRecognitionRequestRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class SavedLanguageRecognitionRequest
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $source_text;

    /**
     * @ORM\Column(type="datetime")
     */
    private $requested_at;

    /**
     * @ORM\OneToMany(targetEntity=SavedLanguageRecognitionDetection::class, mappedBy="savedLanguageRecognitionRequest")
     */
    private $recognitions;

    public function __construct()
    {
        $this->recognitions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSourceText(): ?string
    {
        return $this->source_text;
    }

    public function setSourceText(string $source_text): self
    {
        $this->source_text = $source_text;

        return $this;
    }

    public function getRequestedAt(): ?\DateTimeInterface
    {
        return $this->requested_at;
    }

    public function setRequestedAt(\DateTimeInterface $requested_at): self
    {
        $this->requested_at = $requested_at;

        return $this;
    }

    /**
     * @return Collection|SavedLanguageRecognitionDetection[]
     */
    public function getRecognitions(): Collection
    {
        return $this->recognitions;
    }

    public function addRecognition(SavedLanguageRecognitionDetection $recognition): self
    {
        if (!$this->recognitions->contains($recognition)) {
            $this->recognitions[] = $recognition;
            $recognition->setSavedLanguageRecognitionRequest($this);
        }

        return $this;
    }

    public function removeRecognition(SavedLanguageRecognitionDetection $recognition): self
    {
        if ($this->recognitions->removeElement($recognition)) {
            // set the owning side to null (unless already changed)
            if ($recognition->getSavedLanguageRecognitionRequest() === $this) {
                $recognition->setSavedLanguageRecognitionRequest(null);
            }
        }

        return $this;
    }

    /**
     * @ORM\PrePersist
     */
    public function autoSetRequestedAt()
    {
        $this->requested_at = new \DateTime();
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\OptAd;
use App\Entity\SavedIMGWMeasurement;
use App\Entity\SavedLanguageRecognitionRequest;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MainController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(): Response
    {

        return $this->render('main/index.html.twig', [
            'controller_name' => 'MainController'
        ]);
    }

    /**
     * @Route("/first", name="first")
     */
    public function indexs(): Response
    {
        $em = $this->getDoctrine()->getManager();
        $opts = $em->getRepository(OptAd::class)->findAll();

        return $this->render('main/first.html.twig', [
            'opts' => $opts
        ]);
    }

    /**
     * @Route("/second", name="second")
     */
    public function sec(): Response
    {
        $em = $this->getDoctrine()->getManager();
        $measurements = $em->getRepository(SavedIMGWMeasurement::class)->findAll();

        $url = "https://danepubliczne.IMGW.pl/api/data/synop";

        $json = json_decode(file_get_contents($url));

        $stations = [];
        foreach ($json as $row) 
        {
            array_push($stations, [$row->stacja." (id: ".$row->id_stacji.")", $row->id_stacji]);
        }

        return $this->render('main/second.html.twig', [
            'measurements' => $measurements,
            'stations' => $stations
        ]);
    }

    /**
     * @Route("/thrid", name="thrid")
     */
    public function thr(): Response
    {
        $em = $this->getDoctrine()->getManager();
        $recs = $em->getRepository(SavedLanguageRecognitionRequest::class)->findAllWithRecognitions();

        return $this->render('main/thrid.html.twig', [
            'recs' => $recs
        ]);
    }
}

templates/main/first.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MainController!
{% endblock %}

{% block body %}

	<div class="example-wrapper">
		<h1>OptAd360 Test API</h1>
		<hr><span>Table below holds previously saved results from API. Click Send button to make new request and store it in this history.</span>
		<hr>
		<div>
			<button class="btn d-none d-sm-inline-block btn-primary" onclick="request()">Send Request & write to database</button>
            <button class="btn d-sm-none btn-primary" onclick="request()">Send</button>
			<label for="sel">Currency</label>
			<select name="sel" id="select">
				<option selected value="1">PLN</option>
				<option value="2">EUR</option>
				<option value="3">USD</option>
			</select>
		</div>
		<div class="table-responsive">
			<table class="mt-3 mb-0 table table-secondary table-hover">
				<theadclass="thead-dark">
					<tr>
						<th scope="col">Requested at</th>
						<th scope="col">Curr.</th>
						<th scope="col">URLs</th>
						<th scope="col">Tags</th>
						<th scope="col">Date</th>
						<th scope="col">Est. rev.</th>
						<th scope="col">Ad impr.</th>
						<th scope="col">eCPM</th>
						<th scope="col">Clicks</th>
						<th scope="col">CTR</th>
					</tr>
				</thead>
				<tbody id="hed">
					{% for opt in opts|reverse %}
						<tr>
							<td>{{opt.requestedAt|date('H:m d-m-Y')}}</td>
							<td>{{opt.currency}}</td>
							<td>{{opt.urls}}</td>
							<td>{{opt.Tags}}</td>
							<td>{{opt.date}}</td>
							<td>{{opt.estimatedRevenue}}</td>
							<td>{{opt.adImpressions}}</td>
							<td>{{opt.adEcpm}}</td>
							<td>{{opt.clicks}}</td>
							<td>{{opt.adCtr}}</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>

	</div>
{% endblock %}


{% block javascripts %}
{{ parent() }}

<script>
function request()
{
	let url = "{{path ('getOptAd360') }}";

	$.ajax({
		url: url,
		method: "post", 
		data: JSON.stringify(
			{'currency':$("#select option:selected").text()})
		})
	.done(res => 
	{ 
        if (res == '0')
            alert("Request failed");
        else
        {
            console.log(res);
            let json = JSON.parse(res);
            console.log(json);
            json.data.forEach(function(data)
            {
                let tdHtml = '<td scope="row">now (frontend)</td><td scope="row">'+$("#select option:selected").text()+'</td>';
                data.forEach(function(fe)
                {
                    tdHtml += `<td scope="row">${fe}</td>`
                });

            let trc = document.createElement('tr');
            trc.innerHTML = tdHtml;
            document.getElementById('hed').prepend(trc);
            });
        }
        

		
	});
}
</script>
{% endblock %}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MainController!{% endblock %}

{% block body %}

<a href="{{path('first')}}"><h1>OptAd360 API</h1></a>
<a href="{{path('second')}}"><h1>IMGW API</h1></a>
<a href="{{path('thrid')}}"><h1>DetectLanguage API</h1></a>
   
{% endblock %}

templates/main/second.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MainController!
{% endblock %}

{% block body %}
	<div class="example-wrapper">
		<h1>IMGW API</h1>
		<a href="https://danepubliczne.imgw.pl/">https://danepubliczne.imgw.pl/</a>
		<hr>
		<span>Table below holds previously saved results from API. Click Send button to make new request and store it in this history.</span><hr>
		<button class="btn btn-primary" onclick="request()">Send Request & write to database</button>
		<label for="sel">Station</label>
		<select name="sel" id="select">
			{% for station in stations %}
				<option value="{{station[1]}}">{{station[0]}}</option>
			{% endfor %}
		</select>

		<div class="table-responsive">
			<table class="mt-3 mb-0 table table-secondary table-hover">
				<theadclass="thead-dark">
					<tr>
						<th scope="col">Requested At</th>
						<th scope="col">Station ID</th>
						<th scope="col">Station</th>
						<th scope="col">Date</th>
						<th scope="col">Temp</th>
						<th scope="col">Wind dir.</th>
						<th scope="col">Wind speed</th>
						<th scope="col">Relative Hum.</th>
						<th scope="col">Drop sum</th>
						<th scope="col">Pressure</th>
					</tr>
				</thead>
				<tbody id="hed">
					{% for m in measurements|reverse %}
						<tr>
							<td>{{m.requestedAt|date('H:m d-m-Y')}}</td>
							<td>{{m.stationId}}</td>
							<td>{{m.station}}</td>
							<td>{{m.date}}</td>
							<td>{{m.temp}}</td>
							<td>{{m.windDir}}</td>
							<td>{{m.windSpeed}}</td>
							<td>{{m.relativeHumidity}}</td>
							<td>{{m.dropSum}}</td>
							<td>{{m.pressure}}</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>

	</div>
{% endblock %}


{% block javascripts %}
{{ parent() }}

<script>

function request()
{
	let url = "{{path ('getIMGW') }}";

	$.ajax({
		url: url,
		method: "post", 
		data: JSON.stringify(
			{'stationid':$("#select").val()})
		})
	.done(res => 
	{ 
        if (res == '0')
            alert("Request failed");
        else
        {
            let json = JSON.parse(res);
            console.log(json);
            
            let tdHtml = `<td scope="row">now (frontend)</td><td scope="row">${json.id_stacji}</td><td scope="row">${json.stacja}</td><td scope="row">${json.data_pomiaru} ${json.godzina_pomiaru}</td><td scope="row">${json.temperatura}</td><td scope="row">${json.kierunek_wiatru}</td><td scope="row">${json.predkosc_wiatru}</td><td scope="row">${json.wilgotnosc_wzgledna}</td><td scope="row">${json.suma_opadu}</td><td scope="row">`+ (json.cisnienie == null ? 'unknown' : json.cisnienie) + `</td>`;
               

            let trc = document.createElement('tr');
            trc.innerHTML = tdHtml;
            document.getElementById('hed').prepend(trc);
            
        }
        

		
	});
}
</script>
{% endblock %}

templates/main/thrid.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MainController!
{% endblock %}

{% block body %}

	<div class="example-wrapper">
		<h1>DetectLanguage API</h1>
		<a href="https://detectlanguage.com/">https://detectlanguage.com/</a>
		<hr>
		<span>Table below holds previoulsy saved results from API. Click Send button to make new request and store it in this history.</span>
		<hr>
		<label for='inp'>Type text for language recognition</label><br>
		<textarea class="form-control rounded-0" name='inp' id="input" rows="3"></textarea>
		<button class="btn btn-primary mt-3" onclick="request()">Send Recognition Request & write to database</button>

		<div class="table-responsive">
			<table class="mt-3 mb-0 table table-secondary table-hover">
				<theadclass="thead-dark">
					<tr>
						<th scope="col">Requested At</th>
						<th scope="col">Source Text</th>
						<th scope="col">Recognized language</th>
						<th scope="col">isReliable</th>
						<th scope="col">Confidence score</th>
					</tr>
				</thead>
				<tbody id="hed">
					{% for r in recs|reverse %}
						<tr class="{% if loop.index%2 == 0 %}{% set bg = 'table-warning' %}{% else %}{% set bg = 'table-success' %}{% endif %}{{bg}}">
							<td>{{r.requestedAt|date('H:m d-m-Y')}}</td>
							<td>{{r.sourceText}}</td>
							<td>{{r.recognitions[0].recognizedLang}}</td>
							<td>
								{% if r.recognitions[0].isReliable == 1 %}yes{% else %}no
								{% endif %}
							</td>
							<td>{{r.recognitions[0].confidenceScore}}</td>
						</tr>
						{% for ro in r.recognitions %}
							{% if loop.index != 1 %}
								<tr class="{{bg}}">
									<td></td>
									<td></td>
									<td>{{ro.recognizedLang}}</td>
									<td>
										{% if ro.isReliable == 1 %}yes{% else %}no
										{% endif %}
									</td>
									<td>{{ro.confidenceScore}}</td>
								</tr>
							{% endif %}
						{% endfor %}
					{% endfor %}
				</tbody>
			</table>
		</div>

	</div>
{% endblock %}


{% block javascripts %}
{{ parent() }}

<script>

function request()
{
	let url = "{{path ('getLng') }}";
  if ($("#input").val()== "") return;
	$.ajax({
		url: url,
		method: "post", 
		data: JSON.stringify(
			{'q':$("#input").val()})
		})
	.done(res => 
	{ 
        if (res == '0')
            alert("Request failed");
        else
        {
            let json = JSON.parse(res);
            console.log(json);

            let trc = '';
            
            json.data.detections.forEach(function(detection) 
            {
                let tdHtml = `<td scope="row">${detection.language}</td><td scope="row">${detection.isReliable}</td><td scope="row">${detection.confidence}</td>`;
                
                if(trc == '')
                {
                  trc = '<tr>';
                  trc += '<td scope="row">now (frontend)</td><td scope="row">'+$("#input").val()+'</td>'+tdHtml+'</tr>';
                }
                else
                {
                  trc += '<tr>';
                  trc += '<td scope="row"></td><td scope="row"></td>'+tdHtml+'</tr>';
                }
            });

            $("#hed").prepend(trc+'</tr>');
        }
        

		
	});
}
</script>
{% endblock %}